<section class="breadcrumb-area blog bg-img bg-overlay jarallax"
            style="background-image: url(https://images.unsplash.com/photo-1543709533-c032159da7b0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80);">
            <div class="container h-100">
                <div class="row h-100 align-items-center">
                    <div class="col-12">
                        <div class="breadcrumb-content text-center">
                            <a href="#" class="btn post-catagory">Nature</a>
                            <h2 class="page-title">How medical waste is wreaking havoc on the environment
                            </h2>
                            <div class="post-meta">
                                <span class="post-author">By Yashraj Garg</span>
                                <span class="post-date">June 05, 2023</span>
                            </div>
                            <div class="blog-timer">
                                <p>2 min read</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="alime--blog-area section-padding-80">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-lg-10">
                        <div class="blog-details-text">
                            <p><b>Introduction</b></p>
                            <p>Have you ever stopped to think about the impact of medical waste on the environment? The World Health Organization defines medical waste as "waste generated by healthcare activities," encompassing a wide range of materials, from chemicals to needles and syringes. But what are the consequences of this waste for our planet?</p>
                            <p> Healthcare activities generate a significant amount of waste, with 15% of all medical waste being hazardous and infectious. Not only does this waste contain potentially harmful microorganisms that can infect communities, but it also contributes to environmental pollution, exacerbating the effects of air pollution. A study by Wei et al. (2021) predicts that medical waste in China will reach a staggering 2.7 × 109 kg per year by 2030. Does this mean that the environmental effects will increase in direct proportion to the rise in medical waste? The answer is yes.</p>

                            <div class="my-5">
                                <div class="row">
                                    <div class="col-12 col-lg-8">
                                        <div class="row">
                                            <div class="col-12 col-sm-6">
                                                <div class="backend-content">
                                                    <img class="dots" src="<?=$path;?>./assets/images/core-img/dots.png" alt="Backgraound Image">
                                                    <h2>Blog</h2>
                                                </div>
                                                <img class="mb-10 blog-img1"
                                                    src="https://img.freepik.com/free-photo/hazardous-waste-nature-medical-masks_23-2148764824.jpg?w=900&t=st=1685951947~exp=1685952547~hmac=98fe0b19dc5eb5695082e77d0adda194940b0acf2e716175974b7b1874f99f84"
                                                    alt="hazardous-waste-nature-medical-masks">
                                            </div>
                                            <div class="col-12 col-sm-6">
                                                <img class="mb-10 blog-img1"
                                                    src="https://images.unsplash.com/photo-1587854692152-cbe660dbde88?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=869&q=80"
                                                    alt="How medical waste is wreaking havoc on the environment">
                                            </div>
                                            <div class="col-12">
                                                <img class="mb-10 blog-img2"
                                                    src="https://img.freepik.com/free-photo/minimalistic-science-banner-with-pills_23-2149431091.jpg?w=826&t=st=1685952672~exp=1685953272~hmac=66c3512a4bffc25a42c68c2933fb6aa0f6bc8eadf676f8df37896fb27cdb384c"
                                                    alt="minimalistic-science-banner-with-pills">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 col-lg-4">
                                        <img class="mb-10 blog-img3"
                                            src="https://img.freepik.com/free-photo/coronavirus-protective-medical-equipment-set_53876-165326.jpg?w=360&t=st=1685951913~exp=1685952513~hmac=87ad44df95da94b7f96195857b6f9d5e876c7671a8cadd4c3c40313fe70e5792"
                                            alt="coronavirus-protective-medical-equipment-set">
                                        <div class="backend-content-2">
                                            <img class="dots" src="<?=$path;?>./assets/images/core-img/dots.png" alt="Backgraound Image">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <p>Improper segregation of biomedical waste and the mishandling of various medical waste streams trigger a dangerous domino effect, posing risks to individuals and society as a whole. For instance, different pharmaceutical techniques can produce radioactive particles that pose challenges to air quality. When these particles come into contact with the air, they introduce harmful elements that, when ingested, can have serious health consequences.</p>
                            <p>Fortunately, there are measures we can take to mitigate these issues—specifically, through proper medical waste management techniques. Various disposal methods, such as land disposal, chemical disinfection, and incineration, can be employed. Additionally, we can render radioactive particles inert through chemical processes, minimizing their negative impact on the environment when exposed.</p>
                            <p><b>Conclusion</b></p>
                            <blockquote class="alime-blockquote">
                                <h4>Overall, medical waste has far-reaching consequences for the health and well-being of communities worldwide. It is imperative for us as individuals to understand the significance of employing appropriate techniques for the disposal of biomedical waste. Only then can we ensure a thriving environment for future generations.</h4>
                                <h6>- Yashraj Garg</h6>
                            </blockquote>
                        </div>
                        <div class="post-author-area mt-50 d-flex align-items-center justify-content-between">
                            <ul class="popular-tags">
                                <li class="badges-btn">Climate Change</li>
                                <li class="badges-btn">Sustainability</li>
                                <li class="badges-btn">Net Zero</li>
                            </ul>
                            <div class="post-social-info d-flex align-items-center">
                                <p>Follow Yashraj:</p>
                                <a href="https://www.linkedin.com/in/yashraj-garg-14569b219/" target="_blank"><i
                                        class="fa fa-linkedin" aria-hidden="true"></i></a>
                                <a href="https://www.instagram.com/yashrajgarg_/" target="_blank"><i
                                        class="fa fa-instagram" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>